### ISSUE TITLE
bug: pc로 들어갔을때, 채팅방 리스트에서 + 버튼이 보이지 않습니다. 

### ISSUE THREAD

**Issue by sumi-0011** [prayinforrain/numble-talk#3]
## 버그 상황
pc로 들어갔을때, 채팅방 리스트에서 + 버튼이 보이지 않습니다. 
(모바일 화면에만 + 버튼이 보입니다)

### PC 화면 스크린샷
<img width="926" alt="스크린샷 2023-04-21 오후 2 19 10" src="https://user-images.githubusercontent.com/49177223/233546944-706090b3-ceee-449b-827a-7451d7e06803.png">

### 모바일 화면 스크린샷
<img width="420" alt="스크린샷 2023-04-21 오후 2 19 35" src="https://user-images.githubusercontent.com/49177223/233546982-b1506fd1-1891-46e5-a28d-b57cdea8a21d.png">

**Comment by prayinforrain** [comment]
감사해요 굿 👍👍
